### ISSUE TITLE
Use domain as bucket name and subdomain as prefix for downloading emails from S3

### ISSUE THREAD

**Issue by saiorama** [psiCode/email-client#2]
If a domain does not have subdomains, use the domain name as bucket name
If it has subdomains, use the subdomains in reverse order as prefix inside the bucket by replacing . with /
Ignore port numbers in domain names

Domain| Bucket Name | Prefix
----------|------|------------------------
https://example| example | -n/a-
https://example.com | example.com | -n/a-
https://email.example.com| example.com | email
https://teamA.email.example.co.in| example.co.in | email/teamA
https://teamA.email.example.co.in:3737| example.co.in | email/teamA

(Use Mozilla's [Public Suffix List](https://publicsuffix.org/list/) to solve the last requirement.)

**Comment by saiorama** [comment]
I've created an API to extract tld from a domain based on the PSL linked above.

Use the API so - 
`curl -H 'x-api-key: <API Key>' 'https://api.zeer0.com/v001/tools/public-suffix?domain=https://janata.in'`

I'll send you the API key separately. 

How is it useful?

The domain prefix is the last dot separated segment prior to the TLD. Therefore, for _www.my-website.co.in_, **co.in** is TLD, **my-website** is domain prefix, and **www** is the subdomain.

**Comment by nafeen** [comment]
Awesome!

**Comment by saiorama** [comment]
I just realized that we can manage this entire process of extracting the domain in the Lambda layers. I'm going to close the ticket here and recreate it in [ses-email-client](https://github.com/saiorama/ses-email-client).

**Comment by nafeen** [comment]
Understood. Yeah, that should work as well.
